module Binop01 =

begin (* maybe "main = begin" *)

var x: Int = 100;
var y: Bool = False;

if (x > 30) then
  y = True;
endif

if (x < 50 && y) then
  y = !y;
  x = x + 2;
elsif (!(x == 2)) then  (* need the paren here. *)
  x = x + 3;
  x = x % 23;  (* let's have a (* nested comment test *) too. *)
endif

printInt(x);

end
 (* should I combine these two ends? Or have syntax so that a named
  * terminator ends everything inside of it? nah. *)
end Binop01