(* Binary operator tests *)

proc main()
begin
   var x: Int = 100;
   var y: Bool = #false;

   if (x > 30) then
      y = #true;
   /if

   if (x < 50 && y) then
      y = !y;
      x = x + 2;
   elsif (!x == 2) then  (* x isn't bool *)
      x = x + 3;
   elsif (x || 20) then  (* x still isn't bool *)
      x = x - 27;
   elsif (x < 22222) then
      y = x < y;         (* y isn't int *)
   /if
/proc
