(* integer case statement with constant expression *)

module case04 begin

open stdio;

export proc main() => Int
begin
  var u1: Int = -1;
  var n: Int = 4; (* for non-const error test *)

  case u1
    of 4 then
      printString("It's 4");
    of 5/-4 then
      printString("It's -1 ");
    else
      printString("It's something else. I tell you what");
  endcase

  return 0;
end main

end case04