(* Equality comparison of different types *)

open stdio;
open complex;

proc main() -> Int
begin
  var c1: Complex = {i=1.0, j=3.0};
  var c2: Complex = {i=1.0, j=3.0};
  var c3: Complex = {i=1.0, j=2.0};

  if c1 == c2 then
    printString("c1 and c2 are equal.");
  else
    printString("c1 and c2 are not equal.");
  /if

  if c1 == c3 then
    printString("c1 and c3 are equal.");
  else
    printString("c1 and c3 are not equal.");
  /if

  return 0;
/proc