(* attempt to pass an immutable type as mutable *)
module mutErr03 begin

open stdio;

type Complex is struct
  i: Float,
  j: Float;

proc swapij($c: Complex)
begin
  var temp = c.i;
  c.i = c.j;
  c.j = temp;
  return;
end swapij

export proc main()
begin

  var cpx: Complex = {i=2.0, j=1.111};
  printFloat(cpx.i);
  printFloat(cpx.j);
  swapij(!cpx);
  printFloat(cpx.i);
  printFloat(cpx.j);

end main

end mutErr03
