(* attempt to mutate an argument though passed immutably *)
module mutErr01 begin

open stdio;

type Complex is struct
  mut i: Float,
  mut j: Float;


proc swapij(c: Complex)
begin
  var temp = c.i;
  c.i = c.j;
  c.j = temp;
  return;
end swapij

export proc main()
begin
  var cpx: Complex = {i=2.0, j=1.111};
  printFloat(cpx.i);
  printFloat(cpx.j);
  swapij(cpx);
  printFloat(cpx.i);
  printFloat(cpx.j);

end main

end mutErr01
