(* pass mutable type but try to change immutable field *)
module MutErr04 =

open Stdio;

type Complex = struct
  mut i: Float,
  j: Float;
end Complex

proc swapij(#c: Complex) : Void =
  var temp = c.i;
  c.i = c.j;
  c.j = temp;
  return;
end swapij

export proc main() : Void = 

  var cpx: Complex = {i=2.0, j=1.111};
  printFloat(cpx.i);
  printFloat(cpx.j);
  swapij(#cpx);
  printFloat(cpx.i);
  printFloat(cpx.j);

end main

end MutErr04
