(* passing and returning nullable values *)
module Null04 =

open Stdio;

proc maybeInt(n: Int, i: Int?) : Int? =
  if n > 5 then
    (* should be able to return either subtype of a nullable. *)
    return n;
  else
    return Null;
  endif
end maybeInt


export proc main (): Void =
  (* should be able to pass either subtype of a nullable. *)
  if var i ?= maybeInt(4, Null) then
    printInt(i);
  else
    printString("nope");
  endif
end main

end Null04