(* passing and returning nullable values *)
module null04 begin

open stdio;

proc maybeInt(n: Int, i: Int?) => Int? 
begin
  if n > 5 then
    (* should be able to return either subtype of a nullable. *)
    return n;
  else
    return null;
  endif
end maybeInt


export proc main ()
begin
  (* should be able to pass either subtype of a nullable. *)
  if var i ?= maybeInt(4, null) then
    printInt(i);
  else
    printString("nope");
  endif
end main

end null04
