(* mutually recursive data type *)
module mutrec01 begin

type IntNode is rec struct
   value: Int,
   mut next: FloatNode;

type FloatNode is rec struct
   value: Float,
   mut next: CharNode;

(* Need cycle checking, because this one has no forward refs. *)
type CharNode is rec struct
   value: Byte,
   mut next: IntNode?;

(* This isn't a recursive type. *)
type WholeGraph is struct
   g: IntNode;
   
end mutrec01