(* struct example, initted by record exp after declaration *)
module Struct02 =

open Stdio;

type Complex = struct
  i: Float,
  j: Float;
end Complex


export proc main() : Void = 

  var cpx: Complex; (*  = {i=2.0, j=1.111};*)
  cpx = {i=4.0, j=-1.53};
  (* cpx.j = 3.3; *) (* assignment to immutable field not allowed *)
  cpx = {i=4.1, j=-2.2};  (* reassignment should be fine *)
  printFloat(cpx.i);
  printFloat(cpx.j);

end main

end Struct02
