(* mutable struct initialized with individual field assignments. *)
module struct00 is

type Complex is record
  mut i: Float,
  mut j: Float;
/type
  
/module

(* top-level code *)
open stdio;
open struct00;

proc main() 
do
  var cpx: Complex; 
  (* cpx.i = 4.0; (* NO LONGER WORKS due to non-separate symbols. *)
  cpx.j = -1.53; *)
  cpx = {i=4.0, j=-1.53};
  printFloat(cpx.i);
  printFloat(cpx.j);

/proc


