(* struct example, initted by record exp after declaration *)
(* module struct02 begin *)

open stdio;

type Complex is struct
  i: Float,
  j: Float;

type Cplx is struct
   f: Int,
   j: Int;

proc main()
begin

  var cpx: Complex; (*  = {i=2.0, j=1.111};*)
  cpx = {i=4.0, j=-1.53};
  (* cpx.j = 3.3; *) (* assignment to immutable field not allowed *)
  cpx = {i=4.1, j=-2.2};  (* reassignment should be fine *)
  printFloat(cpx.i);
  printFloat(cpx.j);

end main

(* end struct02 *)
