(* assigning wrong nullable subtype to a union *)

module UnionErr01 =

open Stdio;

type Num = union
  Float?,
  Int;
end Num

export proc main() : Void =
  var u1: Num = 4;
  var u2: Num = 5.5;

  (* should probably be able to do this. *)
  (* var u2: Num = (5.5: Float?); *)

  (* case u1
    of i: Int =>
      printInt(i);
    of f: Float =>
      printFloat(f);
  endcase *)

end main

end UnionErr01