(* assigning wrong nullable subtype to a union *)

module unionErr01 begin

open stdio;

type Num is variant
  | fo: Float?
  | i: Int;

export proc main()
begin
  var u1: Num = Num|i(4);
  var u2: Num = Num|fo(null);

  (* should probably be able to do this. *)
  (* var u2: Num = (5.5: Float?); *)

  (* case u1
    of i: Int =>
      printInt(i);
    of f: Float =>
      printFloat(f);
  endcase *)

end main

end unionErr01