module while01 begin

import stdio;

var i = 14;  (* try some global vars *)
var j: Int = 0;

export proc main() => Int
begin
  while (i >= 0) loop
    j = 2*i+1;  (* declaring j each time through eats memory. Not good. 
                 * could the LLVM optimizer fix it? *)
    stdio::printInt(i);
    i = i - 1;
  endwhile

  stdio::printInt(i);
  stdio::printInt(j);

  return 0;

end main

end while01